"""
primeira_dag
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from airflow.models import Variable
from astro import sql as aql
import pandas as pd
import pendulum

import requests
from airflow.models import Variable
import random

@aql.dataframe(task_id="aleatorio")
def aleatorio_func():
    return random.randint(1,10)

@aql.dataframe(task_id="python_1")
def python_1_func(aleatorio: pd.DataFrame):
    print(aleatorio)
    URL_FULL = str(Variable.get("API")) + str(aleatorio)
    print(URL_FULL)
    response = requests.get(URL_FULL)
    return response.json()["name"]

@aql.dataframe(task_id="python_2")
def python_2_func(python_1: pd.DataFrame):
    print(python_1)

default_args={
    "owner": "Luciano Filho,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="* * * * *",
    start_date=pendulum.from_format("2024-03-23", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "Luciano Filho": "mailto:lvgalvaofilho@gmail.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/clu3h21wy071k01pra3nb36mj/cloud-ide/clu3pa9y3079301m3x1wfx6oe/clu3pbf5n079401m3lelzg8o3",
    },
)
def primeira_dag():
    aleatorio = aleatorio_func()

    python_1 = python_1_func(
        aleatorio,
    )

    python_2 = python_2_func(
        python_1,
    )

dag_obj = primeira_dag()
